### ISSUE TITLE
Image dimensions for bike classification

### ISSUE THREAD

**Issue by lebeli** [Lyleregenwetter/BIKED#4]
Hello Lyle,

I was wondering what image dimension, i.e. resolution, you used for the image classification with the 3-Layer neural network. I could not find the specification in the paper.

Thank you in advance.

**Comment by Lyleregenwetter** [comment]
Hi @lebeli 

The images were 120 (height) x 260 (width).

-Lyle

**Comment by lebeli** [comment]
Would it be reasonable to expect a similar performance on 256x256 images?

**Comment by Lyleregenwetter** [comment]
Yeah, I expect so.
