### ISSUE TITLE
Meaning of categorical parameter "FRONTdiscB type"

### ISSUE THREAD

**Issue by lebeli** [Lyleregenwetter/BIKED#5]
Hello again,

what exactly does the "FRONTdiscB type" parameter (Generic 160mm I.S., Generic 160mm Post and Generic Front Flat Mount) refer to? How do the categories differ?

Kind regards!

**Comment by Lyleregenwetter** [comment]
These are different types of front wheel disc brakes. The different parameters are just different variants that come in the bikecad software or are made by some user

**Comment by lebeli** [comment]
Does this imply, that every bike has front wheel disc brakes? I checked some samples and there are samples that don't seem to have disc brakes.

**Comment by Lyleregenwetter** [comment]
nope, front disc brakes can be turned on or off. The disc brake type parameters will still appear in the data, but will basically just be inactive
