### ISSUE TITLE
The meaning of the features in the dataset

### ISSUE THREAD

**Issue by Whaleye** [Lyleregenwetter/BIKED#6]
Hi,

firstly thank you very much for your work and your code. Now I have a question about the meaning of the features. Because I want to learn more about the relationship between images and parameters. So I want to ask can you provide more details of the dataset so that it is possible to learn about which parameter means what. Thank you so much!

**Comment by Lyleregenwetter** [comment]
Hi Whaleye,

I don't have a comprehensive list, but if you want to investigate the meaning of any particular parameter, I advise that you look into its function in the bikecad software! However, with some luck the parameters you are looking for are in this informal list: https://docs.google.com/spreadsheets/d/1-rOeT-bFhZWLiO0wm6uakQPihaCawp4cJq8QIEMpWcU/edit?usp=sharing

Hope this helps!

**Comment by Whaleye** [comment]
Sorry, I think I can not open this link. Can you please update it?
